version: '3.8'

services:
  smartdb-doc:
    build: .
    container_name: smartdb-doc-linux
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Shanghai
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
